
from sqlalchemy.orm import Session
import models, schemas


def get_employees(db: Session):
    return db.query(models.Employee).all()
# database ka koi bhi operation happens within a particular session. 
# db ek Session object hai – saare DB operations isi session ke through hote hain.
# yahan hum Employee table (models.Employee) par query chala kar sab rows le rahe hain.
# table is in modles.Employee



# 1 employee
def get_employee(db: Session, emp_id: int):
    return (
        db.query(models.Employee).filter(models.Employee.id == emp_id).first()
        )




# creating employee needs full employee details

def create_employee(db: Session, employee: schemas.EmployeeCreate):
    db_employee = models.Employee(name=employee.name, email=employee.email)
    db.add(db_employee)
    db.commit()
    db.refresh(db_employee)  # To get autogenerated id from DB for this employee
    return db_employee






def update_employee(db: Session, emp_id: int, employee: schemas.EmployeeUpdate):
    db_employee = db.query(models.Employee).filter(models.Employee.id == emp_id).first()
    if db_employee:
        db_employee.name = employee.name
        db_employee.email = employee.email
        db.commit()
        db.refresh(db_employee) 
    return db_employee






def delete_employee(db: Session, emp_id: int):
    db_employee = db.query(models.Employee).filter(models.Employee.id == emp_id).first()
    if db_employee:
        db.delete(db_employee)
        db.commit()
    return db_employee

# refresh nahi karna hai because delete kar diya hai, koi data update nahi kiya hai database ke andar.


