from pydantic import BaseModel, EmailStr
from typing import Optional


class EmployeeBase(BaseModel):
    name: str
    email: EmailStr


class EmployeeCreate(EmployeeBase):
    email:Optional[EmailStr] = None
# name is required because thats coming from EmployeeBase Class
# if we think while creating employee email is optional then we can set it as optional here
# id is autogenerated, because in models.py it's defined there as primary key

'''
Pydantic me:
	1.	email: EmailStr
	•	Field required
	•	Value EmailStr hi hona chahiye (None allowed nahi)

	2.	email: Optional[EmailStr]
	•	Field required
	•	Value EmailStr ya None ho sakta hai
	•	Key "email" bhejna zaroori hai
    
	3.	email: Optional[EmailStr] = None
	•	Field not required
	•	Agar bheja to EmailStr ya None
	•	Agar skip kare to default None use hoga
'''


class EmployeeUpdate(EmployeeBase):
    pass


class EmployeeOut(EmployeeBase):
    id: int


    class Config:
        orm_mode = True

