from pydantic import BaseModel, Field, EmailStr
from typing import Optional


class EmployeeBase(BaseModel):
    name: str = Field(..., min_length=3, max_length=30, description="Name must be 3-30 chars")
    email: EmailStr


class EmployeeCreate(EmployeeBase):
    email:Optional[EmailStr] = None
# name is required because thats coming from EmployeeBase Class
# if we think while creating employee email is optional then we can set it as optional here
# id is autogenerated, because in models.py it's defined there as primary key


'''
Pydantic me:
	1.	email: EmailStr
	•	Field required
	•	Value EmailStr hi hona chahiye (None allowed nahi)

	2.	email: Optional[EmailStr]
	•	Field required
	•	Value EmailStr ya None ho sakta hai
	•	Key "email" bhejna zaroori hai
    
	3.	email: Optional[EmailStr] = None
	•	Field not required
	•	Agar bheja to EmailStr ya None
	•	Agar skip kare to default None use hoga
'''


class EmployeeUpdate(EmployeeBase):
    pass




# When user wants to read the data then we send the data so this will be used to send the data.
# but we have to send all the fields of employee including id
class EmployeeOut(EmployeeBase):
    id: int


    class Config:
        orm_mode = True

	    # Since we are reading data so:
		# orm = True will allow Pydantic to read data directly from ORM models(SQLAlchemy models)
        # also enables smooth conversion to json

